// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package modelstore

import (
	"database/sql"
	"encoding/json"
)

type Caches struct {
	ID        int64
	Name      sql.NullString
	Value     sql.NullString
	UpdatedAt sql.NullTime
	Expires   sql.NullTime
}

type MlbGame struct {
	ID           int64
	UpdatedAt    sql.NullTime
	Gametime     sql.NullTime
	GameID       int64
	Description  sql.NullString
	Status       sql.NullString
	Link         sql.NullString
	HomeID       int64
	VisitorID    int64
	HomeScore    sql.NullInt64
	VisitorScore sql.NullInt64
}

type MlbTeam struct {
	ID        int64
	UpdatedAt sql.NullTime
	TeamID    int64
	Name      sql.NullString
	Link      sql.NullString
}

type NhlGame struct {
	ID           int64
	UpdatedAt    sql.NullTime
	Gametime     sql.NullTime
	GameID       sql.NullInt64
	Description  sql.NullString
	Status       sql.NullString
	Link         sql.NullString
	HomeID       int64
	VisitorID    int64
	HomeScore    sql.NullInt64
	VisitorScore sql.NullInt64
}

type NhlTeam struct {
	ID          int64
	UpdatedAt   sql.NullTime
	TeamID      int64
	FranchiseID int64
	Tricode     sql.NullString
	Name        sql.NullString
	Link        sql.NullString
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	ResetCode    sql.NullString
	Data         json.RawMessage
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Status       sql.NullBool
}
