on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'

    - name: Build web binary
      run: go build -o ./bin/free-ent-guide-backend ./cmd/web

    - name: Build CLI binary
      run: go build -o ./bin/cli-free-ent